### ISSUE TITLE
API broken link

### ISSUE THREAD

**Issue by moneymunch** [KateHyoung/UTDEventData#19]
The API registration link is broken. 

https://eventdata.utdallas.edu/signup.

It returns "Registration Failed."

**Comment by MarcusMMS** [comment]
Hello and thank you for your message. We are working to resolve the issue and will notify you when the issue is resolved.

**Comment by MarcusMMS** [comment]
Hello and thank you for your message. I contacted the server person about the issue. They said that the issue appears to be resolved and to please try again. If it does not work, however, please let me know and I will send you an API key.
