### ISSUE TITLE
Quering by event code in Phoenix RT

### ISSUE THREAD

**Issue by ysapolovych** [KateHyoung/UTDEventData#4]
I want to find all events in Phoenix RT with, say, code 90. I see that a dataframe generated by the query does indeed contain a column 'code' with a respective CAMEO code, but 
`tableVar(apikey, 'PHOENIX_RT')` shows no variable with such name. And indeed, I can't query it with returnRegExp (though no error is shown):
```
> evcode <- returnRegExp("5WSDHiyObsBUBu9JR4PVdg5E6lrkStRM", 'PHOENIX_RT', "90", "code")
> evcode
NULL
```
So can this be addressed in any way? An option quering by event code would be awesome!

**Comment by KateHyoung** [comment]
Can you please try this code?
returnRegExp(api_key, "phoenix_rt","090", "code")

**Comment by KateHyoung** [comment]
I am also checking the function, tableVar( ) and put it up on Github once I fix it. Thank you!

**Comment by ysapolovych** [comment]
Thanks for the prompt response! You're right, I missed a digit, but even with the correct code it does not work. The value of evcode is still NULL. So if fixing tableVar( ) could do the thing - it'd be great.

**Comment by KateHyoung** [comment]
I have fixed the function and believe you will not have NULL anymore once throwing the above code in R. 
Thank you for pointing this out.

**Comment by ysapolovych** [comment]
It works well now. Thank you again!
